[build]
  publish = "."
  functions = "functions"

[[edge_functions]]
  function = "admin"
  path = "/api/admin"

[[edge_functions]]
  function = "activate"
  path = "/api/activate"

[[edge_functions]]
  function = "verify"
  path = "/api/verify"
